from django.urls import path

from .views import (
    ai_generation_draft_detail,
    collection_detail,
    collection_goal,
    collection_list,
    confirm_draft,
    custom_study_queue,
    daily_study_queue,
    discard_draft,
    flashcard_bulk_create,
    flashcard_detail,
    flashcard_list,
    generate_flashcards,
    generate_next_batch,
    goals_summary,
    media_confirm,
    media_delete,
    media_upload_url,
    regenerate_draft_cards,
    remove_draft_cards,
    source_document_confirm,
    source_document_detail,
    source_document_upload_url,
    streak_calendar,
    study_queue,
    submit_review,
)

urlpatterns = [
    path('collections/', collection_list, name='collection_list'),
    path('collections/<int:collection_id>/', collection_detail, name='collection_detail'),
    path('collections/<int:collection_id>/flashcards/', flashcard_list, name='flashcard_list'),
    path('collections/<int:collection_id>/flashcards/bulk/', flashcard_bulk_create, name='flashcard_bulk_create'),
    path('collections/<int:collection_id>/study-queue/', study_queue, name='study_queue'),
    path('collections/<int:collection_id>/goal/', collection_goal, name='collection_goal'),
    path('collections/<int:collection_id>/ai-generate/', generate_flashcards, name='generate_flashcards'),
    path(
        'collections/<int:collection_id>/source-documents/upload-url/',
        source_document_upload_url, name='source_document_upload_url',
    ),
    path(
        'collections/<int:collection_id>/source-documents/confirm/',
        source_document_confirm, name='source_document_confirm',
    ),
    path('ai-generate/<int:draft_id>/', ai_generation_draft_detail, name='ai_generation_draft_detail'),
    path('ai-generate/<int:draft_id>/generate-next-batch/', generate_next_batch, name='generate_next_batch'),
    path('ai-generate/<int:draft_id>/regenerate/', regenerate_draft_cards, name='regenerate_draft_cards'),
    path('ai-generate/<int:draft_id>/remove-cards/', remove_draft_cards, name='remove_draft_cards'),
    path('ai-generate/<int:draft_id>/confirm/', confirm_draft, name='confirm_draft'),
    path('ai-generate/<int:draft_id>/discard/', discard_draft, name='discard_draft'),
    path('goals/summary/', goals_summary, name='goals_summary'),
    path('streak/', streak_calendar, name='streak_calendar'),
    path('study/daily/', daily_study_queue, name='daily_study_queue'),
    path('study/custom/', custom_study_queue, name='custom_study_queue'),
    path('flashcards/<int:flashcard_id>/', flashcard_detail, name='flashcard_detail'),
    path('flashcards/<int:flashcard_id>/media/upload-url/', media_upload_url, name='media_upload_url'),
    path('flashcards/<int:flashcard_id>/media/confirm/', media_confirm, name='media_confirm'),
    path('flashcards/<int:flashcard_id>/review/', submit_review, name='submit_review'),
    path('media/<int:media_id>/', media_delete, name='media_delete'),
    path('source-documents/<int:document_id>/', source_document_detail, name='source_document_detail'),
]
