# Generated by Django 4.2.23 on 2026-08-23 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='flashcards.collection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('basic', 'Basic'), ('multiple_choice', 'Multiple choice'), ('typed_answer', 'Typed answer')], max_length=20)),
                ('prompt', models.TextField()),
                ('answer', models.TextField(blank=True, default='')),
                ('options', models.JSONField(blank=True, default=list)),
                ('accepted_answers', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='flashcards.collection')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due', models.DateTimeField()),
                ('step', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('stability', models.FloatField(blank=True, default=None, null=True)),
                ('difficulty', models.FloatField(blank=True, default=None, null=True)),
                ('elapsed_days', models.PositiveIntegerField(default=0)),
                ('scheduled_days', models.PositiveIntegerField(default=0)),
                ('reps', models.PositiveIntegerField(default=0)),
                ('lapses', models.PositiveIntegerField(default=0)),
                ('state', models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('review', 'Review'), ('relearning', 'Relearning')], default='new', max_length=12)),
                ('last_review', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_states', to='flashcards.flashcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_states', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'Again'), (2, 'Hard'), (3, 'Good'), (4, 'Easy')])),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('state_before', models.JSONField()),
                ('state_after', models.JSONField()),
                ('review_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='flashcards.reviewstate')),
            ],
            options={
                'ordering': ['reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='FlashcardMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], max_length=10)),
                ('side', models.CharField(choices=[('prompt', 'Prompt'), ('answer', 'Answer')], max_length=10)),
                ('storage_key', models.CharField(max_length=512)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='flashcards.flashcard')),
            ],
        ),
        migrations.AddIndex(
            model_name='reviewstate',
            index=models.Index(fields=['user', 'due'], name='flashcards__user_id_f3a6ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='reviewstate',
            constraint=models.UniqueConstraint(fields=('user', 'flashcard'), name='unique_user_flashcard_review_state'),
        ),
        migrations.AddIndex(
            model_name='reviewlog',
            index=models.Index(fields=['review_state', 'reviewed_at'], name='flashcards__review__c5dcde_idx'),
        ),
        migrations.AddConstraint(
            model_name='flashcardmedia',
            constraint=models.UniqueConstraint(fields=('storage_key',), name='unique_flashcard_media_storage_key'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['user', 'parent'], name='flashcards__user_id_4498a6_idx'),
        ),
    ]
