# Generated by Django 4.2.23 on 2026-08-31 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flashcards', '0002_collectiongoal_studyday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashcardGenerationDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('basic', 'Basic'), ('multiple_choice', 'Multiple choice'), ('typed_answer', 'Typed answer')], max_length=20)),
                ('learning_request', models.TextField()),
                ('cards', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('discarded', 'Discarded')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_drafts', to='flashcards.collection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_generation_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'collection', 'status'], name='flashcards__user_id_f95bba_idx')],
            },
        ),
    ]
