# Generated by Django 4.2.23 on 2026-08-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_flashcardgenerationdraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardgenerationdraft',
            name='target_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
