# Generated by Django 4.2.23 on 2026-09-20 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flashcards', '0005_generationsourcedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed')], default='in_progress', max_length=12)),
                ('mode', models.CharField(choices=[('random', 'Random cards'), ('selected', 'Selected cards'), ('retake', 'Retake missed cards')], max_length=10)),
                ('time_limit_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('source_labels', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('card_type', models.CharField(choices=[('basic', 'Basic'), ('multiple_choice', 'Multiple choice'), ('typed_answer', 'Typed answer')], max_length=20)),
                ('prompt', models.TextField()),
                ('answer', models.TextField(blank=True, default='')),
                ('options', models.JSONField(blank=True, default=list)),
                ('accepted_answers', models.JSONField(blank=True, default=list)),
                ('selected_option', models.PositiveIntegerField(blank=True, null=True)),
                ('submitted_answer', models.TextField(blank=True, default='')),
                ('self_correct', models.BooleanField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('answered_after_time', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='flashcards.exam')),
                ('flashcard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_questions', to='flashcards.flashcard')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddConstraint(
            model_name='examquestion',
            constraint=models.UniqueConstraint(fields=('exam', 'position'), name='unique_exam_question_position'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['user', '-started_at'], name='flashcards__user_id_6f8366_idx'),
        ),
    ]
