# Generated by Django 4.2.23 on 2026-08-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_google_id'),
    ]

    operations = [
        # default=True here is deliberately different from the model's
        # default=False -- this value only backfills EXISTING rows when the
        # migration runs (so accounts that already exist don't suddenly see
        # onboarding again); new rows created from this point on go through
        # the model's own default=False, per accounts/models.py.
        migrations.AddField(
            model_name='user',
            name='has_seen_onboarding',
            field=models.BooleanField(default=True),
        ),
    ]
