# Generated by Django 4.2.23 on 2026-09-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_has_seen_onboarding'),
    ]

    operations = [
        # Nullable, no backfill needed: existing users never accepted the
        # Terms of Service (they registered before this field existed), so
        # they correctly stay NULL going forward -- unlike
        # has_seen_onboarding below, there's no divergence between the
        # model's default and what existing rows should get.
        migrations.AddField(
            model_name='user',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        # Housekeeping picked up by makemigrations, unrelated to
        # terms_accepted_at: 0003's AddField recorded a one-time
        # default=True (see that migration's own comment) to backfill
        # existing rows without re-showing onboarding, deliberately
        # different from the model's real default=False. This AlterField
        # just brings Django's migration-state bookkeeping back in sync
        # with the model as declared; it doesn't change the column's
        # already-applied data.
        migrations.AlterField(
            model_name='user',
            name='has_seen_onboarding',
            field=models.BooleanField(default=False),
        ),
    ]
