"""
Django settings for eyelearn project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False' if os.environ.get('VERCEL') else 'True') == 'True'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', '')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-local-dev-only-do-not-deploy'
    else:
        raise ImproperlyConfigured('SECRET_KEY environment variable must be set when DEBUG is False.')

ALLOWED_HOSTS = os.environ.get(
    'ALLOWED_HOSTS',
    '127.0.0.1,localhost,.vercel.app',
).split(',')

CSRF_TRUSTED_ORIGINS = os.environ.get(
    'CSRF_TRUSTED_ORIGINS',
    'https://*.vercel.app',
).split(',')

GOOGLE_OAUTH_CLIENT_ID = os.environ.get('GOOGLE_OAUTH_CLIENT_ID', '')

PAYMENT_PROVIDER = os.environ.get('PAYMENT_PROVIDER', 'stripe')
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET', '')
STRIPE_PRICE_ID_MONTHLY_USD = os.environ.get('STRIPE_PRICE_ID_MONTHLY_USD', '')
STRIPE_PRICE_ID_MONTHLY_BRL = os.environ.get('STRIPE_PRICE_ID_MONTHLY_BRL', '')
STRIPE_PRICE_ID_ANNUAL_USD = os.environ.get('STRIPE_PRICE_ID_ANNUAL_USD', '')
STRIPE_PRICE_ID_ANNUAL_BRL = os.environ.get('STRIPE_PRICE_ID_ANNUAL_BRL', '')

FRONTEND_ALLOWED_ORIGINS = os.environ.get('FRONTEND_ALLOWED_ORIGINS', 'http://localhost:3000').split(',')

# Single canonical frontend URL used to build password-reset links (unlike
# FRONTEND_ALLOWED_ORIGINS, which is a list for CORS/redirect validation).
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:3000')

# Resend (https://resend.com) is used to send password-reset emails. Without
# a verified sending domain in the Resend dashboard, RESEND_FROM_EMAIL can
# only deliver to the account's own verified address.
RESEND_API_KEY = os.environ.get('RESEND_API_KEY', '')
RESEND_FROM_EMAIL = os.environ.get('RESEND_FROM_EMAIL', 'onboarding@resend.dev')

# Where the Help page's contact form notifies the team of a new submission.
# Left unset in an environment silently skips that notification email (the
# ContactMessage row and the submitter's confirmation email still go out).
CONTACT_NOTIFICATION_EMAIL = os.environ.get('CONTACT_NOTIFICATION_EMAIL', '')

# Shared secret the Next.js BFF attaches on every outbound call (see
# eyelearn.middleware.InternalApiKeyMiddleware). Required in every
# environment, including local dev -- generate one with
# `python -c "import secrets; print(secrets.token_urlsafe(32))"` and put
# the same value in eyelearn-ui's EYELEARN_INTERNAL_API_KEY.
INTERNAL_API_KEY = os.environ.get('INTERNAL_API_KEY', '')

STORAGE_BUCKET_NAME = os.environ.get('STORAGE_BUCKET_NAME', '')
STORAGE_ACCESS_KEY_ID = os.environ.get('STORAGE_ACCESS_KEY_ID', '')
STORAGE_SECRET_ACCESS_KEY = os.environ.get('STORAGE_SECRET_ACCESS_KEY', '')
STORAGE_ENDPOINT_URL = os.environ.get('STORAGE_ENDPOINT_URL', '')
STORAGE_REGION = os.environ.get('STORAGE_REGION', 'auto')

FSRS_DESIRED_RETENTION = float(os.environ.get('FSRS_DESIRED_RETENTION', '0.9'))
FSRS_ENABLE_FUZZING = os.environ.get('FSRS_ENABLE_FUZZING', 'False') == 'True'


# Application definition

INSTALLED_APPS = [
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'corsheaders',
    'rest_framework',
    'api',
    'accounts',
    'billing',
    'flashcards',
]

AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'eyelearn.middleware.InternalApiKeyMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = FRONTEND_ALLOWED_ORIGINS

ROOT_URLCONF = 'eyelearn.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'eyelearn.wsgi.application'


DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600,
    )
}


AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'django_cache_table',
    }
}

REST_FRAMEWORK = {
    'UNAUTHENTICATED_USER': None,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/min',
        'user': '120/min',
        'register': '5/hour',
        'login': '10/hour',
        'token_refresh': '30/hour',
        'checkout_session': '10/hour',
        'password_reset_request': '5/hour',
        'password_reset_confirm': '10/hour',
        'email_verification_confirm': '10/hour',
        'email_verification_resend': '5/hour',
        'contact_form': '5/hour',
    },
    'DEFAULT_RENDERER_CLASSES': (
        ['rest_framework.renderers.JSONRenderer', 'rest_framework.renderers.BrowsableAPIRenderer']
        if DEBUG else
        ['rest_framework.renderers.JSONRenderer']
    ),
}

STATIC_URL = 'static/'
